export const SET_CHECKIN_TYPE = "SET_CHECKIN_TYPE";
export const SET_SEARCH = "SET_SEARCH";
export const UPDATE_DATA = "UPDATE_DATA";
export const ON_STATE_CHANGE = "ON_STATE_CHANGE";
export const DELETE_WORKFLOW = "DELETE_WORKFLOW";
export const ADD_WORKFLOW = "ADD_WORKFLOW";
